### ISSUE TITLE
Error with resetting password in API

### ISSUE THREAD

**Issue by trystant** [trystant/respond#2]
When making a request to the reset password URL, the following error message appears (screenshot of Google Web Developer Tool console attached):
<img width="1440" alt="screenshot 2016-01-14 22 31 04" src="https://cloud.githubusercontent.com/assets/13509/12344724/892cc074-bb0e-11e5-8676-0810dc9c6d2e.png">

On the server side, there is this stack trace:
```
PHP Fatal error:  Uncaught exception 'Tonic\\MethodNotAllowedException' with message 'No matching method for HTTP method "GET"' in /var/www/html/respond/app/api/vendor/peej/tonic/src/Tonic/Resource.php:191
Stack trace:
#0 [internal function]: Tonic\\Resource->method('POST')
#1 /var/www/html/respond/app/api/vendor/peej/tonic/src/Tonic/Resource.php(64): call_user_func_array(Array, Array)
#2 /var/www/html/respond/app/api/vendor/peej/tonic/src/Tonic/Resource.php(119): Tonic\\Resource->calculateMethodPriorities(Array
#3 /var/www/html/respond/app/api/dispatch.php(66): Tonic\\Resource->exec()
#4 {main}
  thrown in /var/www/html/respond/app/api/vendor/peej/tonic/src/Tonic/Resource.php on line 191
```
I'm trying to figure out the source of the problem, but I only have these Google Groups threads:
* [Can't create a site](https://groups.google.com/forum/#!topic/respond-cms/bJb-pIBDPOU)
* [API Half working](https://groups.google.com/d/topic/respond-cms/WdA7Y7VOc-A)

One potential solution was to add the following rule `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]` to the `$RESPOND_HOME/app/api/.htaccess` file, but that rule is already there.

At one point I changed permissions in the distribution. I'm betting there's a permissions issue somewhere.

**Comment by trystant** [comment]
This was fixed by adjusting `emacs /var/www/html/respond/app/db/user.php` to return the token for the desired user and once logged in, I changed the password. I logged out and tried the forgot password feature and confirmed that it works now
